### ISSUE TITLE
Change from FreeGLUT to GLFW

### ISSUE THREAD

**Issue by EddyLuten** [openglbook/openglbook.com#42]
Change samples and site from using FreeGLUT to GLFW.

**Rationale**
FreeGLUT is not actively being developed and is difficult to set up compared to GLFW. Also, it would be good to be freed from the shackles of the old GLUT holdovers such as a fixed main loop that would be good to get rid of when using more complex future examples.

[GLFW Documentation](http://www.glfw.org/)

**Comment by judepereira** [comment]
Hey @EddyLuten, would you be open to accepting a pull request for GLFW? I'd like to translate the book and the samples to solidify my understanding altogether.

**Comment by judepereira** [comment]
Moreover - I cannot use FreeGLUT - it requires X, which is powered by the XQuartz project, and does not go above OpenGL 2.1 on newer Macs.
