### ISSUE TITLE
no source code

### ISSUE THREAD

**Issue by z00m1n** [openglbook/openglbook.com#48]
I'm on a MacBook Pro using Chrome Version 39.0.2171.71 (64-bit) and there is no source code on the page. Looking at the html page source, there's a e.g. line `<script src="https://gist.github.com/11129276.js"> </script>` which probably is supposed to add the code from github into the page, but - at least here - that doesn't seem to work.

**Comment by EddyLuten** [comment]
Note to self: This seems to be some issue with GitHub authentication and Gist. If you're not logged into GitHub, the gists seem to load fine. Also, once visiting https://gist.github.com/, the gists load on the page.
