### ISSUE TITLE
Include link to blog post RE: building using Visual C++ in preface

### ISSUE THREAD

**Issue by markmnl** [openglbook/openglbook.com#49]
I, and judging from all the answers I found on the Internet - many others, spent a while getting the dependencies setup to get the code working with Visual C++. Unfortunately I only found the blog post afterwards which would have answered all my questions. 

A link to the blog post building with Visual C++ in the Preface, Software Requirements, would be mighty helpful!

**Comment by EddyLuten** [comment]
Fixed in #50
