### ISSUE TITLE
glGenVertexArray() throws Access Violation

### ISSUE THREAD

**Issue by Wr0ngName** [openglbook/openglbook.com#51]
Chapter 2, the call:

    glGenVertexArrays(1, &VaoId);
(`CreateVBO(void)`) without:

    glewExperimental = GL_TRUE;
(`InitWindow(int argc, char* argv[])`) throws an Exception: "Access violation executing location 0x00000000.".

**Comment by whydoubt** [comment]
To clarify, the assignment
`glewExperimental = GL_TRUE;`
needs to occur before the call
`GlewInitResult = glewInit();`

This appears to be due to an issue with GLEW that has been known since 2010, but is finally fixed in the not-yet-released version 2.0.0.

**Comment by EddyLuten** [comment]
This was mentioned in this blog post http://openglbook.com/blog/glgenvertexarrays-access-violationsegfault-with-glew/ in 2011, which was an issue I thought would be fixed promptly - thus my omission of the line in the source text. I can't believe this flag still needs to be included in 2016.
