### ISSUE TITLE
When will the next chapter be ready?

### ISSUE THREAD

**Issue by CarlLee** [openglbook/openglbook.com#52]

**Comment by EddyLuten** [comment]
It's unlikely that this will happen unless someone else writes it. I consider the site to be in a archive mode of sorts.

**Comment by rpxomi** [comment]
It's a pity that happens. I also went in to see if there were going to be more chapters. The book is very good. It made me realize that OpenGL is how data is transported to memory. I did not realize before. Thank you very much.
